export const styles = (theme) => ({
  root: {
    padding: '34px 24px 24px',
    display: 'flex',
    flexDirection: 'column',
    gap: '24px',
    minHeight: 0,
    boxSizing: 'border-box',
    overflow: 'hidden',
    boxShadow: `inset -1px 0 ${theme.palette.fileExplorerThinLineDividerColor}`,
    background: '#F0F1F2',
    '&::before': {
      content: '""',
      position: 'fixed',
      top: 0,
      left: 0,
      width: 360,
      height: 14,
      pointerEvents: 'none',
      background: '#F0F1F2',
      borderRight: `1px solid ${theme.palette.fileExplorerThinLineDividerColor}`,
    },
  },
  topDragArea: {
    position: 'fixed',
    top: 14,
    left: 0,
    width: 360,
    height: 34,
    WebkitAppRegion: 'drag',
    zIndex: 2,
  },
  previewToggle: {
    '& > .MuiSwitch-root': { marginLeft: 8 },
    justifyContent: 'center',
    height: 36,
    borderRadius: 7,
    background: theme.palette.background.paper,
    WebkitAppRegion: 'no-drag',
    '&:hover': { background: '#e5e7e9' },
    '&[data-disabled="true"]': {
      cursor: 'default',
      background: theme.palette.background.paper,
      color: theme.palette.text.disabled,
    },
    display: 'flex',
    alignItems: 'center',
    fontSize: 12,
    fontWeight: 500,
    lineHeight: '18px',
    color: theme.palette.contrastPrimaryMainColor,
    cursor: 'pointer',
    margin: 0,
  },
  liveCanvas: {
    // Keep the video on its own compositor layer during window/fullscreen resize.
    transform: 'translateZ(0)',
    backfaceVisibility: 'hidden',
    width: '100%',
    height: '100%',
    objectFit: 'contain',
    background: 'transparent',
    display: 'block',
    border: 0,
    outline: 'none',
    boxShadow: 'none',
    borderRadius: 0,
  },
  previewMessage: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
    width: 'calc(100% - 32px)',
    zIndex: 1,
    pointerEvents: 'none',
    fontSize: 14,
    lineHeight: 1.5,
    margin: 0,
    padding: 0,
    background: 'transparent',
    color: '#fff',
    textAlign: 'center',
  },
  installMessage: {
    position: 'absolute',
    bottom: 12,
    left: 12,
    right: 12,
    zIndex: 3,
    padding: 14,
    borderRadius: 16,
    background: 'rgba(20, 28, 40, .94)',
    border: 0,
    color: '#fff',
    fontSize: 13,
    lineHeight: 1.6,
    textAlign: 'center',
    overflowWrap: 'anywhere',
    maxHeight: '70%',
    overflowY: 'auto',
    '& button': {
      display: 'block',
      margin: '6px auto 0',
      color: '#a8c5ff',
      borderRadius: 8,
      transition: 'background-color 150ms ease, color 150ms ease',
      '&:hover': {
        backgroundColor: 'rgba(168, 197, 255, .16)',
        color: '#d6e4ff',
      },
    },
  },
  bottomInfo: { width: '100%', flexShrink: 0 },
  deviceArea: {
    flex: 1,
    minHeight: 0,
    width: '100%',
    justifyContent: 'center',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
  },
  screen: {
    border: 0,
    outline: 'none',
    boxShadow:
      '0 8px 22px rgba(25, 35, 50, 0.18), 0 2px 6px rgba(25, 35, 50, 0.08)',
    borderRadius: 12,
    flexShrink: 0,
    overflow: 'hidden',
    position: 'relative',
    background: '#3f3f3f',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#f2f2f2',
    '& > span': { fontSize: 22, fontWeight: 500, marginTop: 12 },
    '& small': { fontSize: 14, marginTop: 6, opacity: 0.7 },
  },
  fullscreenScreen: {
    position: 'fixed',
    top: 0,
    left: 0,
    zIndex: 1400,
    boxShadow: 'none',
    width: '100vw !important',
    height: '100vh !important',
    background: '#101217',
    borderRadius: 0,
    '& $exitFullscreen': { display: 'inline-flex' },
    '& $liveCanvas': { objectFit: 'contain !important' },
  },
  exitFullscreen: {
    display: 'none',
    position: 'absolute',
    top: 24,
    right: 24,
    zIndex: 2,
    color: '#fff',
    background: 'rgba(30, 30, 34, .85)',
    border: '1px solid rgba(255,255,255,.25)',
    borderRadius: 8,
    padding: '8px 14px',
    '&:hover': { background: 'rgba(60, 60, 66, .95)' },
    '& svg': { marginRight: 6 },
  },
  deviceName: {
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  devicePicker: {
    maxWidth: '100%',
    fontSize: 'inherit',
    fontWeight: 'inherit',
    lineHeight: 'inherit',
    textTransform: 'none',
    height: 32,
    padding: '0 8px',
    margin: 0,
    minWidth: 0,
    textAlign: 'left',
    borderRadius: 6,
  },
  devicePickerIcon: {
    display: 'block',
    width: 16,
    height: 16,
    marginLeft: 4,
    flexShrink: 0,
  },
  usbIcon: { fontSize: 40, opacity: 0.75 },
  deviceInfo: { width: '100%' },
  infoRow: {
    padding: 4,
    marginTop: 8,
    borderRadius: 12,
    background: theme.palette.background.paper,
    border: 0,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  model: {
    minWidth: 0,
    flex: 1,
    fontSize: 14,
    lineHeight: '20px',
    fontWeight: 600,
    margin: '0 8px 0 0',
    overflowWrap: 'anywhere',
  },
  actions: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gridColumnGap: 12,
    padding: 0,
    background: 'transparent',
    border: 0,
    marginTop: 0,
    '& > button': {
      minWidth: 0,
      height: 36,
      padding: '6px 8px',
      fontSize: 12,
      fontWeight: 500,
      lineHeight: '18px',
      color: theme.palette.contrastPrimaryMainColor,
      borderRadius: 7,
      background: theme.palette.background.paper,
      '&:hover': { background: '#e5e7e9' },
      '&.Mui-disabled': {
        background: theme.palette.background.paper,
        color: theme.palette.text.disabled,
      },
    },
    '& svg': { fontSize: 18, marginRight: 4 },
  },
  deviceMenu: {
    minWidth: 240,
    maxWidth: 320,
    borderRadius: 10,
    '& .MuiMenuItem-root': { fontSize: 14 },
  },
  menuMessage: { whiteSpace: 'normal', fontSize: 14 },
  deviceListItem: {
    padding: '4px 0',
    '& strong': { display: 'block', fontSize: 14, lineHeight: '20px' },
    '& span': {
      display: 'block',
      marginTop: 2,
      fontSize: 12,
      lineHeight: '18px',
      color: theme.palette.lightText1Color,
    },
  },
  reconnectIcon: {
    display: 'block',
    width: 14,
    height: 14,
    marginLeft: 6,
    opacity: 0.6,
  },
  status: {
    flexShrink: 0,
    whiteSpace: 'nowrap',
    minWidth: 0,
    lineHeight: '20px',
    textTransform: 'none',
    display: 'inline-flex',
    alignItems: 'center',

    height: 32,
    padding: '0 8px',
    borderRadius: 6,
    background: 'transparent',
    fontSize: 12,
  },
  dot: { width: 6, height: 6, marginRight: 7, borderRadius: '50%' },
  storage: {
    display: 'block',
    width: '100%',
    textAlign: 'left',
    color: theme.palette.contrastPrimaryMainColor,
    WebkitAppRegion: 'no-drag',
    marginTop: 8,
    padding: 12,
    borderRadius: 12,
    background: theme.palette.background.paper,
    border: 0,
    transition:
      'background-color 280ms ease, transform 320ms cubic-bezier(0.2, 0, 0, 1)',
    '&:hover': { background: '#e5e7e9' },
    '&:active': {
      background: '#dce0e4',
      transform: 'scale(0.985)',
    },
    '@media (prefers-reduced-motion: reduce)': {
      transition: 'none',
      '&:active': { transform: 'none' },
    },
    '&.Mui-focusVisible': {
      outline: `2px solid ${theme.palette.secondary.main}`,
      outlineOffset: 2,
    },
    '& p': {
      fontSize: 12,
      margin: '2px 0 0',
      color: theme.palette.lightText1Color,
    },
  },
  storageTitle: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    fontSize: 14,
    fontWeight: 500,
  },
  storageForward: {
    width: 16,
    height: 16,
    // Compensate for the SVG's right-side whitespace to align the visible tip.
    marginRight: -6,
  },
  capacity: {
    marginTop: 4,
    lineHeight: '24px',
    '& strong': { fontSize: 18, fontWeight: 500 },
    '& span': { fontSize: 12, color: theme.palette.lightText1Color },
  },
  progress: {
    width: '100%',
    height: 5,
    appearance: 'none',
    border: 0,
    borderRadius: 4,
    overflow: 'hidden',
    marginTop: 4,
    display: 'block',
    '&::-webkit-progress-bar': {
      background: theme.palette.fileExplorerThinLineDividerColor,
    },
    '&::-webkit-progress-value': { background: '#5686e5', borderRadius: 4 },
  },
});
