export const styles = (theme) => ({
  resizeHandle: {
    position: 'absolute',
    right: 0,
    top: 0,
    bottom: 0,
    width: 8,
    cursor: 'col-resize',
    touchAction: 'none',
    WebkitAppRegion: 'no-drag',
    '&::after': {
      content: '""',
      position: 'absolute',
      right: 3,
      top: 8,
      bottom: 8,
      width: 1,
      background: theme.palette.fileExplorerThinLineDividerColor,
    },
    '&:hover, &:focus': {
      background: theme.palette.action.hover,
      outline: 'none',
    },
  },
  tableHeadCell: {
    border: 'none',
    height: 32,
    padding: '0 12px',
    fontSize: 12,
    fontWeight: 500,
    color: theme.palette.lightText1Color,
    boxShadow: `inset 0 -1px ${theme.palette.fileExplorerThinLineDividerColor}`,
    '&:first-child': { padding: '0 7px 0 17px' },
    '& .MuiCheckbox-root': {
      padding: 4,
      '& .MuiSvgIcon-root': { fontSize: 18 },
    },
    '& .MuiSvgIcon-root': { fontSize: 18 },
    backgroundColor: theme.palette.tableHeaderFooterBgColor,
    position: 'sticky',
    top: 0,
    zIndex: 10,
  },
});
