export const styles = (theme) => ({
  root: {
    display: 'grid',
    gridTemplateColumns: '360px minmax(0, 1fr)',
    // Include the drag strip in the clipping box without moving either pane.
    boxSizing: 'border-box',
    marginTop: -14,
    paddingTop: 14,
    height: '100vh',
    overflow: 'hidden',
    color: theme.palette.contrastPrimaryMainColor,
    background: theme.palette.background.paper,
  },
  filesPane: {
    '&[hidden]': { display: 'none' },
    minWidth: 0,
    display: 'flex',
    flexDirection: 'column',
    minHeight: 0,
  },
  filesHeading: {
    // The visible header includes the preceding 14px Titlebar: 14 + 50 = 64px.
    // Include the divider in that total, matching the two 32px rows below.
    boxSizing: 'border-box',
    height: 50,
    minHeight: 50,
    gap: 12,
    flexWrap: 'nowrap',
    flexShrink: 0,
    WebkitAppRegion: 'drag',
    // The final 40px button adds 8px around its 24px icon: 16 + 8 = 24px.
    padding: '0 16px 0 24px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    // Center both groups in the full 64px band, including the 14px drag strip.
    '& > *': { transform: 'translateY(-7px)' },
    borderBottom: `1px solid ${theme.palette.fileExplorerThinLineDividerColor}`,
  },
  headingLabel: {
    position: 'relative',
    top: 3,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    minWidth: 0,
    flex: '1 1 280px',
    '& h1': { fontSize: 20, lineHeight: '26px', fontWeight: 600, margin: 0 },
  },
  transferHint: {
    maxWidth: '100%',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    marginTop: 2,
    fontSize: 11,
    lineHeight: '16px',
    color: theme.palette.lightText1Color,
    marginRight: 12,
  },
  browser: { position: 'relative', flex: 1, minHeight: 0 },
  emptyState: {
    position: 'absolute',
    top: 32,
    bottom: 0,
    left: 0,
    right: 0,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    background: theme.palette.background.paper,
    padding: 24,
    textAlign: 'center',
    overflowY: 'auto',
    '& h2': {
      fontSize: 20,
      fontWeight: 500,
      margin: '12px 0 16px',
      lineHeight: 1.5,
    },
    '& p': {
      fontSize: 13,
      color: theme.palette.lightText1Color,
      margin: '3px 0',
      lineHeight: 1.6,
    },
  },
  connectionGuide: {
    width: '100%',
    maxWidth: 440,
    flexShrink: 0,
    margin: 'auto',
  },
  connectionSteps: {
    listStyle: 'none',
    counterReset: 'connection-step',
    padding: 0,
    margin: 0,
    textAlign: 'left',
    fontSize: 14,
    lineHeight: 1.7,
    '& li': {
      position: 'relative',
      counterIncrement: 'connection-step',
      paddingLeft: 32,
      marginBottom: 8,
      '&::before': {
        content: 'counter(connection-step)',
        position: 'absolute',
        left: 0,
        top: 1,
        width: 24,
        height: 24,
        lineHeight: '24px',
        borderRadius: '50%',
        background: theme.palette.fileDrop,
        color: theme.palette.secondary.main,
        textAlign: 'center',
        fontSize: 12,
        fontWeight: 600,
      },
    },
    '& strong': { fontWeight: 600 },
  },
  connectionHelp: {
    textAlign: 'left',
    paddingTop: 8,
    borderTop: `1px solid ${theme.palette.fileExplorerThinLineDividerColor}`,
    '& strong': { display: 'block', fontWeight: 500, marginBottom: 4 },
  },
  emptyIcon: {
    margin: '0 auto',
    width: 72,
    height: 72,
    borderRadius: 22,
    background: theme.palette.fileDrop,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    '& svg': { fontSize: 36, color: theme.palette.secondary.main },
  },
});
